spring:
  application:
    name: LineUp
  profiles:
    include: server, db, config, security, docs
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    root: info
    org.springframework.security.oauth2: debug

    org.springframework.security: debug
    org.springframework.web: debug
    com.linerup.lineup_backend: debug