spring:
  application:
    name: LineUp
  profiles:
    include: server, db, config, security
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    root: info
    org.springframework.security.oauth2: debug
    com.linerup.lineup_backend: debug