spring:
  application:
    name: LineUp
  profiles:
    include: server, db, config, security

logging:
  level:
    root: info
    org.springframework.security.oauth2: debug
    com.linerup.lineup_backend: debug