spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${oauth.google.client-id}
            client-secret: ${oauth.google.client-secret}
            redirect-uri: https://${base-uri}/login/oauth2/code/google
            scope:
              - profile
              - email
          kakao:
            client-id: ${oauth.kakao.client-id}
            client-secret: ${oauth.kakao.client-secret}
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: https://${base-uri}/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            scope:
              - account_email
              - profile_nickname

          naver:
            client-id: ${oauth.naver.client-id}
            client-secret: ${oauth.naver.client-secret}
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: https://${base-uri}/login/oauth2/code/naver
            scope:
              - name
              - email
          apple:
            client-id: ${oauth.apple.client-id}
            redirect-uri: https://${base-uri}/login/oauth2/code/apple
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Apple
            scope:
              - name
              - email
        provider:
          kakao:
            user-name-attribute: id
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize?response_mode=form_post
            token-uri: https://appleid.apple.com/auth/token
jwt:
  secret:
    key: ${jwt.secret.key}